runtime: java11
inbound_services:
- warmup
auto_id_policy: default
env_variables:
  'JAVA_USER_OPTS': '--add-opens java.base/java.util=ALL-UNNAMED'
handlers:
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: /.*
  script: unused
  login: optional
  secure: optional
